import { describe, expect, it } from 'vitest';
import { tiptapToTelegram } from '../tiptap-to-telegram.js';

/* eslint-disable-next-line @stylistic/js/max-len --
   Длинная константа, читать не нужно, хранить так проще */
const content = JSON.parse('[{"type":"paragraph","content":[{"type":"text","marks":[{"type":"bold"}],"text":"ueyrghi"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"italic"}],"text":"erogij"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"underline"}],"text":"woeriugh"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"strike"}],"text":"woerifrjh"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"code"}],"text":"woeifj"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"spoiler"}],"text":"woeihjf"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"bold"}],"text":"woeifn "},{"type":"text","marks":[{"type":"bold"},{"type":"strike"}],"text":"woerifj"},{"type":"text","marks":[{"type":"bold"}],"text":" woefij"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"italic"}],"text":"woiefj "},{"type":"text","marks":[{"type":"italic"},{"type":"underline"}],"text":"owiejf"},{"type":"text","marks":[{"type":"underline"}],"text":" weiufn"}]},{"type":"codeBlock","attrs":{"language":null},"content":[{"type":"text","text":"oreigjnpoerkg"}]},{"type":"blockquote","content":[{"type":"paragraph","content":[{"type":"text","text":"lsrgnj"}]},{"type":"paragraph","content":[{"type":"text","text":"epork"},{"type":"text","marks":[{"type":"spoiler"}],"text":"g "},{"type":"text","marks":[{"type":"spoiler"},{"type":"strike"}],"text":"erkmg"},{"type":"text","marks":[{"type":"spoiler"}],"text":" wpoerg"},{"type":"text","text":" wpoef"}]}]},{"type":"paragraph","content":[{"type":"text","marks":[{"type":"mention","attrs":{"href":"https://t.me/wlkergn","target":"_blank","rel":"noopener noreferrer nofollow","class":"cursor-pointer"}}],"text":"@wlkergn"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"hashtag"}],"text":"#erkbn"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"cashtag"}],"text":"$KDF"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"bot_command"}],"text":"/ernm"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"email","attrs":{"href":"mailto:ev@jewpeorij.lnjf","target":"_blank","rel":"noopener noreferrer nofollow","class":"cursor-pointer"}}],"text":"ev@jewpeorij.lnjf"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"link","attrs":{"href":"https://example.com","target":"_blank","rel":"noopener noreferrer nofollow","class":"cursor-pointer"}}],"text":"example.com"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"phone_number","attrs":{"href":"tel:+12345678901","target":"_blank","rel":"noopener noreferrer nofollow","class":"cursor-pointer"}}],"text":"+12345678901"},{"type":"text","text":" "},{"type":"text","marks":[{"type":"text_link","attrs":{"href":"https://example.com","class":"cursor-pointer"}}],"text":"ldtkrhnj"}]}]');

describe('tiptapToTelegram', () => {
  it('should convert tiptap tree to string and telegram message entities', () => {
    expect(tiptapToTelegram(content)).toMatchSnapshot();
  });
});
