name: Common CI/CD

on:
  workflow_call:

jobs:

  changes:
    runs-on: ubuntu-latest
    outputs:
      common: ${{ steps.filter.outputs.common }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          common:
            - 'common/**'

  lint:
    needs: changes
    if: ${{ needs.changes.outputs.common == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/lint
      with:
        working-directory: common

  tests:
    needs: changes
    if: ${{ needs.changes.outputs.common == 'true' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/test
      with:
        working-directory: common

  deploy:
    needs: [lint, tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: common
    steps:
    - uses: actions/checkout@v4
    - name: remove tests
      run: find ./src/ -type d -name __tests__ -exec rm -rf {} +
    - uses: ./.github/actions/setup
      with:
        working-directory: common
    - name: build
      run: pnpm package
    - name: remove unnecessary files
      run: |
        find . -mindepth 1 -maxdepth 1 \
          -type f -not -name 'package.json' -exec rm -rf {} + -or \
          -type d -not -name 'dist' -exec rm -rf {} +
    - name: deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SOURCE: common
        TARGET: ${{ secrets.REMOTE_TARGET }}
