on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: "/assets/, README.md, .gitignore"
        SCRIPT_AFTER: |
          echo ps aux | grep [n]ode
          kill -9 $(ps aux | grep [n]ode | awk '{print $2}')
          echo ps aux | grep [n]ode
          echo pwd
          cd ${{ secrets.REMOTE_TARGET }}
          echo pwd
          echo ls -al
          pnpm install
          pnpm run start
